version: 2.1

description: "CI for the golang-iot package."

executors:
  default:
    description: "The official CircleCI Go Docker image."
    parameters:
      tag:
        description: "The `circleci/golang` Docker image version tag."
        type: string
        default: "latest"
    docker:
      - image: circleci/golang:<< parameters.tag >>

commands:
  install:
    description: "Install Go in your build (for amd64 Linux)."
    parameters:
      version:
        description: "The Go version."
        type: string
        default: "1.13.4"
    steps:
      - run:
          name: "Install Go."
          command: |
            curl -sSL "https://dl.google.com/go/go<< parameters.version >>.linux-amd64.tar.gz" | sudo tar -xz -C /usr/local/
            echo "export PATH=$PATH:/usr/local/go/bin" >> $BASH_ENV
  load-cache:
    description: "Load cached Go modules."
    parameters:
      key:
        description: "The cache key to use. The key is immutable."
        type: string
        default: "go-mod"
    steps:
      - restore_cache:
          keys:
            - << parameters.key >>-{{ checksum "go.mod"  }}
  save-cache:
    description: "Save Go modules to cache."
    parameters:
      key:
        description: "The cache key to use. The key is immutable."
        type: string
        default: "go-mod"
    steps:
      - save_cache:
          key: << parameters.key >>-{{ checksum "go.mod"  }}
          paths:
            - "/go/pkg/mod"
  mod-download:
    description: "Run go mod download"
    steps:
      - run:
          name: "go mod download"
          command: "go mod download"
  test:
    description: "Run go test./..."
    steps:
      - run:
          name: "go test"
          command: |
            go test ./... -timeout 120s -coverprofile cp.out
            go tool cover -html=cp.out -o coverage.html
            bash <(curl -s https://codecov.io/bash)

jobs:
  test:
    executor: default
    steps:
      - install
      - load-cache
      - mod-download
      - save-cache
      - test