version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/jacob-ebey/golang-iot
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./... -timeout 120s -coverprofile cp.out
      - run: go tool cover -html=cp.out -o coverage.html
      - run: bash <(curl -s https://codecov.io/bash)